ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ com.dif.ApplicationKt.module ]
    }
}
jwt {
    secret = "dif_metepec_secret_2024_hidalgo"
    secret = ${?JWT_SECRET}
    issuer = "dif.metepec.gob.mx"
    issuer = ${?JWT_ISSUER}
    audience = "dif-app-users"
    audience = ${?JWT_AUDIENCE}
    realm = "DIF Metepec"
}
database {
    url      = "jdbc:mysql://roundhouse.proxy.rlwy.net:33350/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    driver   = "com.mysql.cj.jdbc.Driver"
    user     = "root"
    password = "pqgVXixEukoPCwTJcVlDFSrSrqXftugk"
}
